Resources:
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      # Completamente opcional, recordemos que DynamoDB no requiere esquemas
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      # Necesario para definir indice principal
      # Como si fuera una base de datos normal, este seria nuestro primary key
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Configuramos la capacidad de lectura/escritura de la tabla
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      # Si tuvieramos nombres dinamicos (por ejemplo, segun ambiente, lo podemos configurar aca)
      TableName: users

  UsersSimpleTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      # Completamente opcional, recordemos que DynamoDB no requiere esquemas
      # Necesario para definir indice principal
      # Como si fuera una base de datos normal, este seria nuestro primary key
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Configuramos la capacidad de lectura/escritura de la tabla
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      # Si tuvieramos nombres dinamicos (por ejemplo, segun ambiente, lo podemos configurar aca)
      TableName: usersSimple